# Generated by Django 2.1.1 on 2018-10-06 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='break',
            name='task',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
