# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-09 17:19
from __future__ import unicode_literals

import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AlterField(
            model_name='task',
            name='body',
            field=models.TextField(blank=True, max_length=1000),
        ),
    ]
